//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Registro
{
    internal class DatatTypeAttribute : Attribute
    {
        private DataType password;

        public DatatTypeAttribute(DataType password)
        {

            this.password = password;
        }
    }
}