//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {

        [Required(ErrorMessage = "Introduzca un correo")]
        [DisplayName("Correo")]
        public string correo { get; set; }
        [Required(ErrorMessage = "Introduzca un correo")]
        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        public string contraseña { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Confirmar contraseña")]
        [Compare("contraseña")]
        public string confirmedPassword { get; set; }
    }
}
